name: test
on: push

permissions:
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v6

      - name: Configure registry
        run: |
          cat <<EOF > .npmrc
          @remarkablemark:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install package
        run: npm install @remarkablemark/test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List package
        run: npm ls @remarkablemark/test

      - name: Use package
        run: node -p 'require("@remarkablemark/test").hello()'
